### ISSUE TITLE
alex3 registering webhook with SDK - cannot read property 'id' of null

### ISSUE THREAD

**Issue by gnanda17** [syncup-chat/SDK#2]
I am using the latest package of hblockus:syncup on alex3.

I am calling the registerWebhook method from server/main.js via the following line. This is called after the emailArray is initialized:
'Meteor.call('registerWebhook', 'notification');'
I am using the latest version of hblockus:syncup for the SDK on alex3.
(https://github.com/syncup-chat/templates/blob/master/templates/server/main.js Line 18 for reference).

I get an error at line 139 of the SDK. Cannot read property 'id' of null
Line 139 refers to  var session = Sessions.findOne({sid: this.connection.id});

Not sure what the root cause / my bug is as yet. This is one of the first lines in registerWebhook pre the http call so I am assuming its not related to my eventType param.

Full error:
Exception from sub templates id EpBC5AiN8Ty9Eo5vq TypeError: Cannot read property 'id' of null
App 1739 stdout: I20160705-22:30:53.825(-4)?     at [object Object].registerWebhook (packages/hblockhus:syncup/syncupSDK_server.js:139:42)
App 1739 stdout: I20160705-22:30:53.825(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
App 1739 stdout: I20160705-22:30:53.826(-4)?     at packages/ddp-server/livedata_server.js:1617:18
App 1739 stdout: I20160705-22:30:53.826(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
App 1739 stdout: I20160705-22:30:53.827(-4)?     at Server.apply (packages/ddp-server/livedata_server.js:1616:45)
App 1739 stdout: I20160705-22:30:53.827(-4)?     at Server.call (packages/ddp-server/livedata_server.js:1559:17)
App 1739 stdout: I20160705-22:30:53.827(-4)?     at Subscription.<anonymous> (server/main.js:18:24)
App 1739 stdout: I20160705-22:30:53.828(-4)?     at Computation.<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:313:1)
App 1739 stdout: I20160705-22:30:53.828(-4)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
App 1739 stdout: I20160705-22:30:53.829(-4)?     at packages/meteor/dynamics_nodejs.js:123:1

**Comment by hblockhus** [comment]
This.connection is undefined. Are you calling registerwebhook from the
server? That won't work as there's no connection and no way to verify the
email

On Tuesday, July 5, 2016, Girish notifications@github.com wrote:

> I am using the latest package of hblockus:syncup on alex3.
> 
> I am calling the registerWebhook method from server/main.js via the
> following line. This is called after the emailArray is initialized:
> 'Meteor.call('registerWebhook', 'notification');'
> I am using the latest version of hblockus:syncup for the SDK on alex3.
> (
> https://github.com/syncup-chat/templates/blob/master/templates/server/main.js
> Line 18 for reference).
> 
> I get an error at line 139 of the SDK. Cannot read property 'id' of null
> Line 139 refers to var session = Sessions.findOne({sid: this.connection.id
> });
> 
> Not sure what the root cause / my bug is as yet. This is one of the first
> lines in registerWebhook pre the http call so I am assuming its not related
> to my eventType param.
> 
> Full error:
> Exception from sub templates id EpBC5AiN8Ty9Eo5vq TypeError: Cannot read
> property 'id' of null
> App 1739 stdout: I20160705-22:30:53.825(-4)? at [object
> Object].registerWebhook
> (packages/hblockhus:syncup/syncupSDK_server.js:139:42)
> App 1739 stdout: I20160705-22:30:53.825(-4)? at maybeAuditArgumentChecks
> (packages/ddp-server/livedata_server.js:1704:12)
> App 1739 stdout: I20160705-22:30:53.826(-4)? at
> packages/ddp-server/livedata_server.js:1617:18
> App 1739 stdout: I20160705-22:30:53.826(-4)? at [object
> Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> App 1739 stdout: I20160705-22:30:53.827(-4)? at Server.apply
> (packages/ddp-server/livedata_server.js:1616:45)
> App 1739 stdout: I20160705-22:30:53.827(-4)? at Server.call
> (packages/ddp-server/livedata_server.js:1559:17)
> App 1739 stdout: I20160705-22:30:53.827(-4)? at Subscription.
> (server/main.js:18:24)
> App 1739 stdout: I20160705-22:30:53.828(-4)? at Computation.
> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:313:1)
> App 1739 stdout: I20160705-22:30:53.828(-4)? at runWithEnvironment
> (packages/meteor/dynamics_nodejs.js:110:1)
> App 1739 stdout: I20160705-22:30:53.829(-4)? at
> packages/meteor/dynamics_nodejs.js:123:1
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/syncup-chat/SDK/issues/2, or mute the thread
> https://github.com/notifications/unsubscribe/AES1LSgvdwCUoxmMrCH5C9AKHDa57obgks5qSxY3gaJpZM4JFtQn
> .

## 

Heather Blockhus
iOS Developer | Syncup Communications Inc.

**Comment by gnanda17** [comment]
got it thanks yes thats my bug then.

**Comment by hblockhus** [comment]
If it needs to be done from the server we will have to rethink the SDK

On Tuesday, July 5, 2016, Girish notifications@github.com wrote:

> got it thanks yes thats my bug then.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/syncup-chat/SDK/issues/2#issuecomment-230658713, or mute
> the thread
> https://github.com/notifications/unsubscribe/AES1LX0_esh5eDC3u64G3rdXlnDFBXo5ks5qSxg-gaJpZM4JFtQn
> .

## 

Heather Blockhus
iOS Developer | Syncup Communications Inc.

**Comment by gnanda17** [comment]
well in this case its an away message that gets sent if you are not present within a certain duration like 30 seconds.

So once you have already set an away message with the widget, I need to be able to get notifications on the webhook regardless of whether the widget is open on the client side. 

If calling registerWebhook from the client side still means the webhook notifications are persistent on the server  side even if the app is not active then Im fine. If not, let me know.

**Comment by hblockhus** [comment]
Yes once a webhook is registered it can fire at any time :)

On Tuesday, July 5, 2016, Girish notifications@github.com wrote:

> well in this case its an away message that gets sent if you are not
> present within a certain duration like 30 seconds.
> 
> So once you have already set an away message with the widget, I need to be
> able to get notifications on the webhook regardless of whether the widget
> is open on the client side.
> 
> If calling registerWebhook from the client side still means the webhook
> notifications are persistent even if the app is not active then Im fine. If
> not, let me know.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/syncup-chat/SDK/issues/2#issuecomment-230659422, or mute
> the thread
> https://github.com/notifications/unsubscribe/AES1LZxvVtu3sG9QsC-YZgub3yJBUNMcks5qSxm3gaJpZM4JFtQn
> .

## 

Heather Blockhus
iOS Developer | Syncup Communications Inc.
